// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gigabee-posts/Affinity.tsx": () => import("../components/mockups/gigabee-posts/Affinity.tsx"),
  "./components/mockups/gigabee-posts/Canary.tsx": () => import("../components/mockups/gigabee-posts/Canary.tsx"),
  "./components/mockups/gigabee-posts/GpuSpeed.tsx": () => import("../components/mockups/gigabee-posts/GpuSpeed.tsx"),
  "./components/mockups/gigabee-posts/HmacReceipts.tsx": () => import("../components/mockups/gigabee-posts/HmacReceipts.tsx"),
  "./components/mockups/gigabee-posts/ModelHash.tsx": () => import("../components/mockups/gigabee-posts/ModelHash.tsx"),
  "./components/mockups/gigabee-posts/RepDecay.tsx": () => import("../components/mockups/gigabee-posts/RepDecay.tsx"),
  "./components/mockups/gigabee-posts/Watchdog.tsx": () => import("../components/mockups/gigabee-posts/Watchdog.tsx")
};
